### ISSUE TITLE
Horizon variable 

### ISSUE THREAD

**Issue by yomuevans** [tomvdb/satellite-server#3]
On every function there's a variable thats needed (horizon).What is it?

**Comment by tomvdb** [comment]
Hi,

The horizon variable is basically used to specify minimum elevation for that function. For example, if you calculate future passes and specify 30 as the horizon then it will ignore passes less than 30 degrees. Hope that is the information you are looking for :)

T

**Comment by tomvdb** [comment]
I'm closing this ticket, but feel free to create a new ticket if you have more questions.

T
